burnash/gspread

README.md
The documentation for `oauth2client` is piss-poor, so I worked through [one of their examples](https://github.com/google/oauth2client/blob/master/samples/oauth2_for_devices.py) to make a valid credentials object. Because there are other libraries that speak OAuth 2.0 and feature better documentation than `oauth2client`, this change might make it easier for people to use `gspread`.
=> Clarified what goes into the OAuth2Credentials object

gspread/exceptions.py, gspread/httpsession.py
I know the usage is deprecated but this Exception is still used in httpsession.py so for now it should at least do what it was intended for
=> Fixed HTTPError usage

gspread/models.py
This avoids issuing one API request per cell to retrieve the Cell
objects after the insertion row. This provides a significant speed-up
for insertions at the beginning of large sheets.
=> Altered insert_row semantics to utilize range

gspread/models.py
Removed the _fetch_cells call for each method. This eliminates the
adverse effect on runtime for large worksheets.
Fixes #285, #190, #179, and #113
=> Optimized row_values and col_values

gspread/models.py, tests/test.py
Thank you for making such an incredibly easy to use api I still think certain special methods could make life just a little easier. 
My addition allows for iteration through a spreadsheet's worksheets. I understand if you do not like this implementation and would rather have people use the worksheets() method for iteration instead. 
I see issue #271 has asked for supporting keys. I will happily add this as well.
Kind regards,
Marc
=> Iterworksheets

docs/oauth2.rst
Directly call `encode` on the `str` rather than implicitly through bytes.
=> DOC: documentation about encoding private_key

docs/oauth2.rst
Oauth2client version 2.0.0 removed SignedJwtAssertCredentials, which is referenced in your authorization readme. I've updated OAuth2.rst to now properly describe how to authorize with oauth2client 2.0.0 using a replacement method, ServiceAccountCredentials.
=> oauth2 documentation update

gspread/httpsession.py
Without this fix, you see following log message on every request to a spreadsheet:
...INFO|requests.packages.urllib3.connectionpool|connectionpool.py:756|_new_conn()|Starting new HTTPS connection (1): spreadsheets.google.com
Creating HTTPS connections is expensive. So this fix improves the overall performance significantly.
See issue #380.
=> Fixed HTTPSession to use request sessions so that connection pool is used

gspread/models.py
'A0' cell label should not work with `get_int_addr()`
@burnash, can you review please?
=> Improve regex pattern for cell_addr

.travis.yml, gspread/models.py, gspread/utils.py, tests/test.py
Since now `gspread.Worksheet.get_all_records` method can handle parameter default_blank that will be used to convert blank cells to something except empty string (default behavior) or zero (if `empty2zero=True`).
=> Make get_all_records return empty cells as None

gspread/models.py, tests/test.py
This fairly simple PR adds an interface convenience to `Worksheet.range`.  In master, range only accepts range strings like 'A1:C4'.  As a result, I regularly find myself doing things like `ws.range(ws.get_addr_int(1, 1) + ':' + ws.get_addr_int(4, 3)`.  This PR just makes it so that `range` can accept integer sequences _in addition_ to the current behavior.  So, e.g., I can just do `ws.range((1,1,4,3))` after this.
I could also change it to use `*args` instead, allowing either `ws.range('A1:C4')` or `ws.range(1,1,4,3)`, but I wasn't sure if there's a preference against `*args` in `gspread`'s API or not.
=> Let range accept integers

gspread/models.py, tests/test.py
The implementation uses that same idea as the one in `insert_row` method (just shifts rows below up and removes the last row).
=> Added del_row method (and test for it)

gspread/models.py
Let's suppose that one have a spreadsheet which values after the inserted row are prefixed by single quote (to avoid formula's evaluation). Then someone inserts a row before it. And then the single quote become lost. To avoid it there is a one-line patch in the pull request.
=> Fix losing input_value data from following cells in insert_row

gspread/client.py
There was an error that the request to insert permissions defaulted to form type, I changed it to be 'application/json' which is accepted by Google.
=> Fix error when inserting permissions.

gspread/httpsession.py
Found a problem when trying to upload data containing unicode, and this is a working solution.
**Now**, I can't say I did any sort of proper testing (only Python 2.7.11, no more cases than my one), though as later in the code there is explicitly `data.encode('utf-8')` this doesn't strike me as an immediately stinky solution.
=> Decode request data as utf-8 by default

gspread/v4/client.py
The current implementation only fetches 100 sheets. I have significantly more than that so I ran into this issue. This commit should allow to fetch all of the sheets for a given user.
It's possible that in the future someone will want to also be able to leverage the `corpora` param which does:
```
Comma-separated list of bodies of items (files/documents) to which the query applies. Supported bodies are 'user', 'domain', 'teamDrive' and 'allTeamDrives'. 'allTeamDrives' must be combined with 'user'; all other values must be used in isolation. Prefer 'user' or 'teamDrive' to 'allTeamDrives' for efficiency.
```
For now I left it out so it's using the default
=> Fetch all spreadsheets in Spreadsheet.list_spreadsheet_files

gspread/v4/client.py
Currently, I can open a spreadsheet located in a team drive by key or url, but not by name. This issue occurs due to the `client.list_spreadsheet_files()` function not having the ability to list team drive files by default.
This PR fixes that issue by enabling team drive files to be listed by default. The ability to list existing spreadsheets outside of team drives is unaffected by this change.
More documentation here: https://developers.google.com/drive/v3/web/enable-teamdrives
=> Open team drive sheets by name

gspread/models.py, gspread/utils.py
#538 
The google API specifies that if the cell `value` is None then no updates will happen in the sheet. Thus, I swapped out the defaultdicts for regular dictionaries and used `.get` for accessing the values (thereby defaulting to None instead of an empty string).
=> Bugfix 538: default cell values to None instead of empty string

gspread/models.py
Looks like there were some copy/paste errors in the documentation. (Documentation currently shows info for value_render_option in methods that actually take value_input_option).
=> Fix parameter typos in docs

gspread/client.py, gspread/models.py
The with_link attribute (https://developers.google.com/drive/api/v2/reference/permissions) (API doc) 
This PR:
- Adds a `with_link` kwarg to `gspread.client.insert_permission`
- Adds a `with_link` kwarg to `gspread.models.Spreadsheet.share`
- By default, `with_link` is set to false (so publicly accessible spreadsheets are publicly findable), but when it is sent to true, then publicly accessible spreadsheets are only accessible for users with the link.
=> Add with_link attribute when sharing / adding permissions

gspread/client.py, tests/test.py
Adds a method to copy spreadsheets, as requested in Issue #158. This is the same functionality as Pull Request #459 but reworked much like @burnash suggested.
Usage example:
```
spreadsheet_copy = client.copy(key, title="Copied Sheet", copy_permissions=True)
```
A title for the new spreadsheet can be specified optionally; the default is "Copy of <original_title>".
`copy_permissions=True` will share the new spreadsheet with everyone who had access to the original. This can be slow for sheets that are shared with many users and is disabled by default.
=> A method to copy spreadsheets

gspread/models.py
Added data length checking to prevent `IndexError` in `.get_all_records()` method of `Worksheet` class. This is a small fix for the issue #629.
<sub>
// Sorry for the second similar pull request
</sub>
=>  Fixed IndexError in Worksheet.get_all_records()

setup.py
* `python_requires` helps pip install the right version for the running Python
* Trove classifiers makes it clear on PyPI which versions are supported
=> Clarify supported versions

gspread/models.py
Fixes a few "gsperad" typos and the docstring :type for `worksheet`'s `title` param (from int to str)
=> Fix typos and docstring :type

gspread/models.py
If there is an item in a worksheet's permissions list that does not have an `emailAddress` attribute, a `KeyError` will be raised in this listcomp. This issue can be solved by using dict.get() notation that will return `None` if the emailAddress key does not exist.
=> Stop keyerror on permissions list comprehension

gspread/client.py
This PR adds the supports team drives parameter to permissions insertion method for GSpread, allowing GSheets to be shared that are in Team Drives
=> Fix for sharing from Team Drives

gspread/utils.py
This fix is for the case then list of cell passed to sheet-update_cell are not top-left conner of upate rect
=> Fix update_cell on non rect cell list

gspread/client.py, tests/test.py
This allows user to get all spreadsheets that contain (case
insensitive) the string that is passed in.
=> Fix usage of client.openall when a title is passed in

gspread/models.py, tests/cassettes/WorksheetTest.test_append_row_with_empty_value.json, tests/cassettes/WorksheetTest.test_append_row_with_empty_value_and_table_range.json, tests/test.py
To address #537 this PR adds two parameters to `Worksheet.append_row()`:
- `table_range`
- `insert_data_option`
This lets the user specify exactly which logical table the Sheets should use to append the row.
=> Add more parameters to `Worksheet.append_row()`

gspread/models.py
Resolve #716 
Regarding the issue, when a worksheet is named similar to A1 notation the requesting URL to the google API v4 could be misunderstood.
For example, if the worksheet is named `v1` the request in `get_all_value` would be
https://sheets.googleapis.com/v4/spreadsheets/[sheet]/values/v1
This breaks the method since the request would only return one value which is the value of the cell `V1`.
A simple fix is to make `get_all_value` follows the [A1 notation](https://developers.google.com/sheets/api/guides/concepts#a1_notation) that the worksheet name should be enclosed by a single quotation.
```
data = self.spreadsheet.values_get("'%s'" % self.title)
```
Originally from master branch, the test already fails with 2 errors on
* `test_values_batch_get`
* `test_values_get`
(The result of …
=> Fix get_all_value does not follow A1 notation.

gspread/models.py
Solves issue #687. Added param index in add_worksheet method
to set index of the newly created worksheet
=> Issue #687 : Add feature to set position of worksheet

gspread/models.py
Hi,
When the sheet name is in A1 Notation, get_all_values only return value from one single cell.
Wrapping them with quotes (like this 'A1') fixes the issue. In case of sheet name already contains a single quotes, we need to escape it with another single quote.
=> When Sheet names in A1 Notation, get_all_values fetching from one cell alone #636

gspread/models.py
Hi, I want to provide function delete multi-rows on sheet
=> Allow delete multi rows

gspread/models.py
Added an append_rows function. This was added to avoid hitting quota limits when adding multiple rows
=> add append_rows function

gspread/models.py
In order to make the process of adding multiple rows to a spreadsheet easier, I've added an add_rows method that allows the user to add multiple rows at once, thus decreasing execution time (less API calls) and overcoming the API write limit.
=> Added add_rows method to simplify the procedure of adding multiple rows

gspread/models.py, tests/test.py
Various fixes to the `merge_cells` function including:
- Allowing A1 range name notation
- Fixing tests so it actually tests it works
- Add merge_type parameter
=> Improve merge_cells and add merge_type parameter

gspread/utils.py
Fixes #744
python3.9 fails if loading gspread.util
Steps to reproduce the behavior:
docker run -it python:3.9.0a5-buster
import("os").system("bash")
pip install gspread
exit
import gspread.util
=> Support old and new collections.abc.Sequence

gspread/models.py, gspread/utils.py, tests/cassettes/WorksheetTest.test_update_and_get.json
1. Extend `utils.absolute_range_name` to handle missing `range_name` parameter.
2. Wrap sheet name in single quotes and escape single quotes.
3. Use `utils.absolute_range_name` throughout `gspread.models` to construct proper range names.
=> Fix sheet names quoting

gspread/utils.py
`gspread.authorize()` fails when using the example from google colab [External Data](https://colab.research.google.com/notebooks/io.ipynb#scrollTo=sOm9PFrT8mGG):
```python
from google.colab import auth
auth.authenticate_user()
import gspread
from oauth2client.client import GoogleCredentials
gc = gspread.authorize(GoogleCredentials.get_application_default())
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-c377298b0a7e> in <module>()
----> 1 gc = gspread.authorize(GoogleCredentials.get_application_default())
2 frames
/usr/local/lib/python3.6/dist-packages/gspread/utils.py in convert_credentials(credentials)
55 
56     raise TypeError(
---> 57         'Credentials …
```
=> Fix `TypeError` when using gspread in google colab

gspread/client.py
Quick development in order to be able to create a spreadsheet within an existing drive folder.
It will allow to have an organized drive when creating spreadsheets at scale.
=> [#678] Add option folder_id when creating a spreadsheet

gspread/models.py
Fixed index error for `endIndex` object in `delete_rows(start_index, end_index)`:
`end_index - 1` -> `end_index`
Fixed comment standard
=> Fix: delete_rows() index error

gspread/models.py
Method `delete_columns(start_index, end_index)`:
Deletes multi columns from the worksheet at the specified index.
param `start_index`: Index of a first column for deletion.
param `end_index`: Index of a last column for deletion.
=> Added delete_columns(start_index, end_index)

gspread/models.py, tests/cassettes/CellTest.test_a1_value.json, tests/test.py
Now it is possible to fetch cell addres in A1 notation by
accessing 'address' attribute of a cell instance
closes #757
=> [#757] Add ability to fetch cell address in A1 notation

gspread/__init__.py, gspread/auth.py, setup.py, test-requirements.txt
This is a first attempt to implement a simplified authentication for gspread. Inspired by excellent [gspread-pandas](https://github.com/aiguofer/gspread-pandas) I'd like to cut down the boilerplate for constructing credentials, so you can get the authorized client instance in your code with just:
```
import gspread
gc = gspread.oauth()
```
On the first run, this will look for OAuth 2.0 Client credentials in `~/.config/gspread/credentials.json`, open a browser window with the application authorization request, get the user's consent and store authorized credentials in the config directory. Next runs will use stored credentials.
Open questions:
1. Credentials security.
2. Default scope.
3. With this added convenience, should client credentials replace service accounts as recommended flow in …
=> Simplified OAuth2 flow

gspread/models.py
* Extract common code from `delete_rows()` and `delete_columns()` into `delete_dimension()`
* Deprecate `delete_row()`
=> Add Worksheet.delete_dimension()

gspread/__init__.py, gspread/auth.py
Simplify auth with service accounts. This PR adds `gspread.service_account()` which wraps `Credentials.from_service_account_file` cutting down initialization code.
So instead of 
```python
import gspread
from google.oauth2.service_account import Credentials
scopes = ['https://spreadsheets.google.com/feeds',
'https://www.googleapis.com/auth/drive']
credentials = Credentials.from_service_account_file(
'path/to/the/downloaded/file.json', 
scopes=scopes
)
gc = gspread.authorize(credentials)
```
You put your service account key in `~/.config/gspread/service_account.json` and `service_account()` does the rest:
```python
import gspread
gc = gspread.service_account()
```
=> Add `auth.service_account()`

gspread/models.py, tests/test.py
Naturally when we deal with Google Spreadsheets we'd like
to operate with letters (in A1 notation), rather then decimal
row/col addressing mode. This patch adds an ability to create
cells using A1 notation, eg.:
cells = [Cell.from_address(f'A{i}', value=i) for i in range(1, 10)]
self.sheet.update_cells(cells)
=> Add ability to create cell instance using A1 notation

gspread/models.py
Adds multiple rows to the worksheet at the specified index and populates it with values
=> Adds multiple rows with index

docs/advanced.rst, gspread/client.py
This fixed https://github.com/burnash/gspread/issues/773
cc @burnash I'd like to suggest using Authlib instead of `google.auth`. With Authlib, you just need to add very little code for the auth part in gspread. Check out: https://blog.authlib.org/2018/authlib-for-gspread
=> Allow auth to be None. Fix #773

gspread/models.py
=> Add insert_cols method to worksheet

docs/user-guide.rst
Updated in Using gspread with NumPy
hearder --> header (with correct spelling of header)
=> Updated user-guide.rst - correct header spell

gspread/models.py, tests/test.py
Closes: #50 
Add the 'insert_note' and 'clear_note' feature.
Notice:
The request to set a note on a cell with an empty string clears the note.
The 'insert_note' function only accepts string as note content
In the test I add I wanted to insert a note and some how through a different process check that the note is inserted but I could not find a way to verify the presence of the note.
I ran a couple of tests myself:
- Insert a note with a text of size 1MiB => works, slow to complete but works
- Over 1GiB text length it times out and an exception is triggered
- I works on _merged_ cells as well
Credits:
Thanks to @archeg that first provided a solution
Thanks to @hexvolt that provided the source code adapted to gpsread
Signed-off-by: Lavigne958 <lavigne958@gmail.com>
=> Add insert_note feature (#50)

docs/oauth2.rst
Hello,
the library provides two methods of auth: [service_account](https://github.com/dmytrostriletskyi/gspread/blob/master/gspread/auth.py#L158) and [service_account_from_dict](https://github.com/dmytrostriletskyi/gspread/blob/master/gspread/auth.py#L187). `service_account_from_dict` was added last year in [this pull request](https://github.com/burnash/gspread/pull/785), but wasn't documented. At least, I have not found anything:
So, this pull requests adds some documentation for the `service_account_from_dict` function to [auth using service account documentation section](https://gspread.readthedocs.io/en/latest/oauth2.html#for-bots-using-service-account). I have built it locally, it looks like:
If there is something I should add, just tell me. Thank you in advance! :)
=> Document dictionary credentials auth

docs/oauth2.rst, gspread/auth.py
While `load_credentials()` allows for user's custom credentials path for service account credentials, `oauth()` doesn't but as discussed in #826 it looks like it is something several users would appreciate.
Given that `oauth()` simply wraps around `load_credentials()` it seems pretty straightforward to just allow `oauth()` to recieve an optional filename.
- `oauth()` gets a an oprional `credentials_filename` argument which is then passed down to `load_credentials()` and defaults to `DEFAULT_AUTHORIZED_USER_FILENAME` so that the change is backward compatible with current documented usage.
- Adds documentation snippets
- Closes #826 
- I named the argument `credentials_filename`, however, I see that you folks generally just use `filename`, happy to keep things consistent here
- I also have …
=> feat: pass a filename to oauth()

gspread/models.py, gspread/utils.py
This PR adds a more flexible alternative to `get_all_values()`:
```python
worksheet.get_values()
worksheet.get_values('A:B')
worksheet.get_values('A2:C10')
worksheet.get_values('my_range')
```
=> Add get_values() to Worksheet

gspread/models.py, gspread/utils.py, tests/test.py
When requesting the numeric value of a cell using `.numeric_value` benefit from the function
`numericise` to auto-cast to a python numeric value if possible.
Return None in case `ValueError` could not cast.
Update function `numericise` to convert spreadsheet number format `2,000,000.01`
to python convertible format => `2000000.01`.
Closes #132 
=> Autocast numeric values to python int or float

gspread/models.py
Regardless of what the end user put as `value_input_option`, it always resulted in "RAW".
=> Fixed a bug with insert_row

gspread/client.py, gspread/models.py
On a call to `open` or `openall` methods we use the GoogleDrive API,
set the list of fields to retrieve and retrieve `createdTime` and `modifiedTime`.
This allows us to get the creation and last modified time of a SpreadSheet.
When using `open_by_key` or `open_by_url` we do not use the GoogleDrive API,
this prevent us from accessing this informaiton, if a user tries to access the `creationTime` or
`lastUpdateTime` property of a SpreadSheet then query the GoogleDrive API to get it.
Benefit from that call to update SpreadSheet metadata on the way.
Closes #332
=> Improvement: Fetch SpreadSheet creation and lastUpdate time.

gspread/models.py
Seems like worksheets only allow ranges in A1 form when retrieving data, although the v4 API works just fine if a named range is passed.  I've just tweaked range extends retrieval a bit to rely on what is returned by the API server if no A1 range is being passed.
=> Allow fetching named ranges from worksheets.

docs/oauth2.rst
Simply following the steps in the documentation `Authentication : For End Users: Using OAuth Client ID`, didn't work for me to give `gspread` access to my Google Sheets.
I figured out that what was wrong, and simply adding my Google account mail to the `Test users` section in the `OAuth consent screen` configuration solved the problem. Otherwise, I was getting the following error in the browser asking me for authentication:
> Error 403: access_denied. The developer hasn’t given you access to this app.
I have searched through the [Issues](https://github.com/burnash/gspread/issues?q=is%3Aissue+is%3Aopen+error+403) and [StackOverflow](https://stackoverflow.com/search?tab=newest&q=%5bgspread%5d%20error%20403) and didn't find anything really matching this docu issue, thus this PR.
Rendering …
=> Update documentation Authentication:For End Users: Using OAuth Client ID

.github/CONTRIBUTING.md, tox.ini
In order to run the test suite with the command `make test` tox must
pass the env variables to `nosetests`.
the following env variables are so far the only variables necessary to run the tests
- GS_RECORD_MODE: to change the recoding mode
- GS_CREDS_FILENAME: to specify you credentials to reach google API
closes #878
=> Bug-fix - use Makefile to run tests

gspread/auth.py
#847 allows users to use custom path for authorized user credentials.
With current implementation, when I call `gspread.auth.oauth()` with custom path,
`oauth()` reads credentials from the given path correctly, but if credentials file is missing,
it authorizes user and store the credentials to the default path (`~/.config/gspread/credentials.json`),
not the custom path!
According to the docs, this behavior is incorrect:
https://github.com/burnash/gspread/blob/master/docs/oauth2.rst
> If you want to store the credentials file somewhere else, specify the path to `authorized_user.json`
This PR fixes `store_credentials()` in `gspread.auth.oauth()` to store creds correctly when `authorized_user_filename` is passed to  `gspread.auth.oauth()`.
=> store creds correctly when authorized_user_filename is passed to gspread.auth.oauth()

gspread/models.py, tests/test.py
Enables the possibility to get the worksheet by it's Id. This approach could be more robust because the worksheets ids never changes and it´s really easy to get it from the URL by looking the for the "**gid**" parameter value
New method:
get_worksheet_by_id
=> Added feature get_worksheet_by_id

docs/oauth2.rst, gspread/auth.py
=> Improvement: Allow users to provide a custom credentials file to oauth()

gspread/client.py
If the `folder_id` is located in a shared drive, this parameter
must be `True` for the API to find the folder.
This does not have any effect in regular drives, keep it
set to `True`.
duplicate of #865 
closes #778
=> Improvement - allow creation of spreadsheets in shared drives

gspread/client.py
When comparing value in `if` statement, when that value
should be a boolean use `if value is True :` instead of `if value :`
because any type of variable/object would meet the `True` condition
in the second case but only `True` would meet the `True` condition
on the first case.
In the case of `copy_permission` we expect a boolean of value `True`
only.
closes #892
=> Fix client.copy copy_permission argument compare

docs/user-guide.rst, gspread/models.py, tests/test.py
based on previous PR #790  from @GastonBC.
`find` method should return `None` in case of no matching cell.
This would make it more user-friendly to use.
Instead of sample code like:
```python
try:
cell = worksheet.find(query)
except CellNotFound as e:
cell = None
if cell is None:
```
We could simply have:
```python
cell = worksheet.find(query)
if cell is None:
```
this is motivated by the fact that the result of `find` is used and (possibly) checked returning `None` makes more sense as the user would check the value and try to access it.
Thanks @GastonBC for original PR
=> find method return none

gspread/utils.py
In numericise if the given value has a comma `,`, when trying
to convert it to a number do not overwrite the original
with the new string without comma, if it is not a number
we lost the original string with the comma inside.
closes #901 
=> Bugfix - in numericise do to overwirte original value

gspread/utils.py
- I fixed the following typo:
- spell of a word in a comment.
- type of a return value.
- a return value will be an integer, not a string.
=> fix docstring and typo

.github/workflows/lint_python.yml, HISTORY.rst, test-requirements.txt, tests/cell_test.py, tests/client_test.py, tests/test.py, tox.ini
Because Travis CI is no longer running on PRs.
Output: https://github.com/cclauss/gspread/actions
=> GitHub Action to lint Python code

.github/workflows/lint_python.yml, docs/conf.py, gspread/__init__.py, gspread/auth.py, gspread/utils.py, gspread/worksheet.py, tests/client_test.py
Now that we have run `black` and `isort`, most flake8 tests pass.
This PR makes minor changes so that flake8 tests all pass except one that is incompatible with black.
* https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8
=> Add more flake8 tests

gspread/worksheet.py
=> Avoid IndexError when row_values() returns an empty row

gspread/worksheet.py
Docstring contain argument `major_dimension` which is not
part of the API, remove it.
closes #829
=> Bugfix - remove wrong argument in `batch_update` docstring

gspread/worksheet.py
Expose worksheet index property.
closes #804
=> Improvement - Add `Worksheet.index` property

gspread/auth.py
In store_credentials function, create the DEFAULT_CONFIG_DIR defined from the get_config_dir() function if it doesn't currently exist.
=> Create default config directory if not exists

docs/oauth2.rst
Currently, the link in the documentation on https://docs.gspread.org/en/latest/oauth2.html#using-signed-credentials links to:
https://console.cloud.google.com/project
However, that link gives you the following error:
> There is a temporary block on your account. This happens when Google detects requests from your network that may have been sent by malicious software, a browser plug-in, or script that sends automated requests.
>Retry in a few minutes.
By removing the `/project` from the URL, the link works and allows users to properly get to the console.
=> Update the link to the Google Developers Console

gspread/client.py
Enables passing `folder_id` to `open` to allow users to identify and open spreadsheet based on the spreadsheet name and ID of parent folder. This enables users to reuse duplicate spreadsheet names in different Drive folders and still be able to access spreadsheets using name.
(I implemented this as a patch with an open source project as we wanted the functionality already and using it successfully. [This](https://gitlab.com/howtobuildup/phoenix/-/merge_requests/129/diffs) is the PR for it, which includes integration style tests that make live calls to Drive and Sheets API that covers the new functionality.)
=> Implement `open` sheet within Drive folder

HISTORY.rst, tox.ini
when running codespell skip documentation resuling build folder.
closes #960
=> Codespell skip docs build folder

docs/oauth2.rst
Fix documentation for method `oauth_from_dict` and provide
a larger example of the dict to pass to the method.
fixes #974
=> Fix documentation about oauth

gspread/client.py, gspread/urls.py, tests/cassettes/ClientTest.test_copy.json
When copying a spreadsheet, if `copy_comments` is True
copy all the comments from original spreadsheet.
When requesting all the comments, the API limit the maximum size of
a page to 100 comments.
Request only the necessary fields from the list of current comments,
to create the new comments iterate over all the comments and push them directly,
no need to change anything.
Recorded the new requests for the tests suite.
closes #978
=> Copy comments when during spreadsheet copy

gspread/client.py
Add the option to specify (or unset) a timeout on the client
This allows users to timeout early if needed or have longer requests
closes #977
=> Add timeout to client

gspread/spreadsheet.py
Add a new method to list all protected ranges.
This method can't be tested in our test suite because it requires to
create a new spreadsheet with a protected range. This requires us to add
the email address used to record the test interactions to create a valid
protected range. This leads to my personal service account leaked in GH.
It has been tested manually and works fine.
Closes #999
=> add method list protected ranges

gspread/worksheet.py, tests/cassettes/WorksheetTest.test_hide_columns_rows.json, tests/worksheet_test.py
Add new method that allows the user to explicitly hide rows or columns.
Ass new method that allows the user to explicitly unhide rows or
columns.
This feature does not include any _listing_ method, because the listing
is not in the metadata of the `SpreadSheet` or the `Sheet`, it will
require to list all the data in the sheet and list all of them
then check if the flag `hiddenByUser` is set. This is a lot of
processing and with very large data set this can take some time
For a result that is only visible using the UI.
closes #1006
=> Add method to hide rows/columns

gspread/spreadsheet.py, tests/cassettes/SpreadsheetTest.test_update_title.json, tests/spreadsheet_test.py
This PR adds a new function Spreadsheet.update_title that allows one to rename a spreadsheet with a new title.
A new test case for the function has also been added and while there is no explicit test case for this, I checked and verified manually that this will also update file names in the Web UI of a folder in google drive.
=> Add ability to rename Spreadsheets (via a new Spreadsheet.update_title)

.github/workflows/release.yaml
Try to reduce the necessary steps to make a new release. Use this new
github action to:
1. run linter and tests
2. generate package
3. create new github release and upload packages
4. publish new packages to PyPi
The pre-required human steps are:
1. change the version number
2. fill the file HISTORY.RST
3. push new commit
4. create tag
5. push tag -> this will trigger the release process
I double checked every steps, everything looks correct, but we'll only know for sure during the next release :wink: 
closes #971
=> Automate releases

gspread/worksheet.py
In method `get_all_record` if a given set of headers is passed
and contains extra values that are not part of the current worksheet
we display an error message that contains these extra values.
previously: a & b => will display all common values from the 2 sets
now: a - b => will display values in set a and not in set b
closes #1027
=> Fix error message in `get_all_records`

gspread/client.py, gspread/exceptions.py, gspread/spreadsheet.py, gspread/utils.py
Add feature to export a spreadsheet to a PDF
And I have some questions about...
- Supporting to export a spreadsheet to other types of files (for all file types listed in Google API docs) 
- Writing test for exporting ( How should I write test for export? )
closes #1035
=> feat: Download PDF from Spreadsheet #1035

gspread/worksheet.py
Add a new method to delete a protected range.
In order to retrieve the `ID` of a protected range, use the method
`gspread.Spreadsheet.list_protected_ranges`.
closes #998
=> Add method to delete a protected range

gspread/auth.py
The oauth flow `gspread.auth.console_flow` has been deprecated by
google. It will simply not succeed.
Currently: add a warning for the end-user about this changes.
Later: remove the deprecated method.
closes #1044
=> Add warning about deprecated oauth flow

gspread/client.py, gspread/spreadsheet.py
The process to transfer ownership of a file has been updated.
It now requires an acceptation from the new owner.
Add a method to transfer the ownership, which sets the right parameters
on the current permission.
add a method to accept the ownership, which set the new type as owner
on the current permission.
The API currently does not accept creating new permissions with the
parameter `pendingOwner` set to `true`. One must create first the permission
then edit it.
closes #1053
=> Add method to transfer / accept ownership of a spreadsheet

HISTORY.rst, gspread/__init__.py, gspread/auth.py, gspread/client.py
This is a pull request to implement a documented feature described in https://github.com/burnash/gspread/issues/1074
I have reviewed the submitting guidelines and I believe this follows all guidelines. (The exception is that it does not provide coverage: However unless I am mistaken there seems to be no tests for this functionality yet, and while this is a noble project, it's not the focus of this pull-request 😁 This feature is passive, it introduces no functionality, it is just a conduit to use the existing `gspread.client.BackoffClient`). Happy to make any modification necessary!
**Is your feature request related to a problem? Please describe.**
As noted, Google introduced [usage limits](https://developers.google.com/sheets/api/limits). While the behavior seems to not be well defined …
=> Add `client_factory` parameter to `auth` methods

gspread/spreadsheet.py
when listing all the protected ranges of a worksheet, if the
`sheetid` does not exists, do not return an empty list.
Instead raise an exception as the ID is wrong.
If the ID is correct try to extract the protected ranges if empty
return an empty list.
closes #1050
=> Fix `list_protected_ranges`

docs/api/exceptions.rst, gspread/exceptions.py, gspread/utils.py, tests/utils_test.py
Add a new method to convert the letter identifying a column
into its index.
This allows users to use the method `Worksheet.col_values` using
a letter to identify the column but passing through this new method
allows to safely convert it to the right index.
closes #1073
=> Add function to convert column letter to column index

gspread/utils.py, gspread/worksheet.py, tests/utils_test.py
Function `numericise_all` can ignore some columns
and skip the value at that specific index.
previously used to
1. get the values to ignore on that row
2. iterate over each value of the row
3. if the value is in the list of ignoring values skip it.
Issue: if a row contains twice the same value and the user would like
to ignore one of the two then the other one is ignored too.
Instead use the index to compare if the value at that index should
be skipped or not.
Closes #1069
=> Fix function `numericise_all`

docs/oauth2.rst
There is an extra pair of curly brackets in the code sample
in the documentation about the function `oauth_from_dict`.
closes #1087
=> Fix documentation about `oauth_from_dict`

gspread/worksheet.py, tests/cassettes/WorksheetTest.test_insert_row.json, tests/worksheet_test.py
(see also: pr #1079, closes #1091)
Hi! I've gone ahead and done up the code.
As for tests, I'm not entirely sure what to do, since I understand there's no way to access the properties of a sheet, which means here's no way to check whether the properties were correctly inherited from the desired row (correct me if I'm wrong). So I simply added some tests to check the behaviour when called with different indices (i.e. check that an exception is being thrown with invalid combos of `inherit_from_before` and row index).
=> inherit_from_before option for insert_row/insert_rows

docs/conf.py, docs/user-guide.rst, tests/worksheet_test.py
There are small typos in:
- docs/conf.py
- docs/user-guide.rst
- tests/worksheet_test.py
Fixes:
- Should read `that` rather than `shat`.
- Should read `worksheet` rather than `workshseet`.
- Should read `gspread` rather than `gpsread`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

gspread/worksheet.py
=> Fix typo in `Worksheet.batch_format` method

gspread/worksheet.py
when using numeric boundaries, extract the full given range
and not just the top left corner.
This allows a user to set/update/clear a complete range.
closes #1103
=> Fix `clear_note` method when using numeric boundaries

gspread/client.py
There is a typo in the permissions:create API payload. As in the [drive API v3 documentation](https://developers.google.com/drive/api/v3/reference/permissions/create), the payload should be _sendNotificationEmail_ instead of _sendNotificationEmails_. As a result, the API call would always send a notification email to the share person, even a False has been passed in method parameter notify.
=> Fix a typo in the permissions:create API payload

gspread/urls.py
When requesting the URL of a spreadsheet using
`spreadsheet.url` it should return a valid URL
to be used in a web browser. This should use the
`docs.google.com` website and not `sheets.googleapis.com`.
closes #1102
=> Fix spreadsheet URL

gspread/spreadsheet.py
When using the method `Spreadsheet.share()` return the newly created permission so user don't have to list the permissions to get it.
closes #1109
=> Return created permission on `Spreadsheet.share()`

gspread/client.py
closes #1113
I didn't add any tests as I took a look at the current test code and it looked like more than I wanted to get into. Probably they should get added, but if someone feels more qualified then they can start off of this commit.
Without this change, my client code of `sheet.share(DOMAIN, perm_type="domain", role="writer")` fails. With this change, my client code works.
=> (fixed #1113) Supply correct Google API v3 permission for domains

gspread/client.py
=> update parent forlder for `client.copy` method

gspread/worksheet.py
returns `properties["hidden"]` which is a boolean for whether the sheet is hidden.
closes #1139
=> isSheetHidden method added to worksheet.py

setup.py, test-requirements.txt
do not require a specific version of `google-auth` and `google-auth-oauthlib`. keep the same minimum version required like before, this works fine. If needed, pip can resolve the dependencies and use more recent versions, they will work fine too, it has been tested.
Previously when encountered dependency version issue it was due to `google-auth-oauthlib` that required a new import from `google-auth` but did not raise its own minimum required version.
Now that it has been fixed on their side we don't have any more issues.
closes #1145
=> Fix dependencies required version

gspread/worksheet.py
If the property is not set then it means its value is `False`.
closes #1149
=> Fix: `hidden` property might not be set from the API

gspread/worksheet.py, tests/worksheet_test.py
Fixes #1041
I removed the method, the according test and also run the tests, the format command and the lint command so everything seems to be in order.
I am not sure if I should update the documentation somehow though.
=> Remove deprecated method delete_row

gspread/spreadsheet.py
Closes #1104
Added a delete by Worksheet Id method in the Spreadsheet Class
=> #1104: added a delete by worksheet id method

gspread/client.py
Not fully certain about some of the type hints, especially regarding `Client.request()`.
=> Initial typing in client.py

gspread/worksheet.py
closes #1167 
I did not add a new exception, simply fix the code to return a consistent result if none of the values are set.
=> Handle cases when rgbColor is not set

gspread/worksheet.py
Solves the issue https://github.com/burnash/gspread/issues/1193
Closes #1193
=> Fix rows_auto_resize in worksheet.py by removing redundant self

gspread/utils.py, gspread/worksheet.py, tests/cassettes/WorksheetTest.test_get_all_values_date_time_render_options.json, tests/worksheet_test.py
This started as a spelling change - I updated "formating" to "formatting for `gspread.utils.DateTimeOption`
I added a test for `date_time_render_option` as there did not seem to be one. I found that the conflict behaviour of this kwarg with `value_render_option` was different to how it was in the docs:
Docs:
Actual behaviour:
If both are set, and `value_render_option` is set to `ValueRenderOption.formatted`, then an API error is thrown by Google's API.
Thus, I have included this in the test, and updated the documentation to reflect this.
In summary:
- Fixed spelling `DateTimeOption.formated_string` -> `DateTimeOption.formated_string`
- Added test `test_get_all_values_date_time_render_options`
- Added test cassette
- Updated documentation for `date_time_render_option`
- changed `note` to …
=> Spelling fix & update docs with date_time_render_option behaviour

tox.ini
tox was taking a long time to run.  This was because it was checking all the files in my python virtual environment, in `./env`.
The [.gitignore](https://github.com/burnash/gspread/blob/master/.gitignore#L9) suggests that a python virtual environment should be called `env`, which is what mine is.
I have added a skip/ignore to the lint/format commands, so they no longer look in `./env`. 
This also has the benefit that they are much faster to run (around 8 secs to lint, 5 secs to format).
=> CLEANUP: cleanup tox.ini, and ignore ./env

gspread/utils.py, tests/worksheet_test.py
I add sketch types for `utils.py` but have following issues:
OAuth2Credentials, AccessTokenCredentials, GoogleCredentials, ServiceAccountCredentials are optional and only needed for oauth2client, so cannot be resolved as a type.
Currently, I have to use the following code to make it work:
```python
def _convert_oauth(credentials: Any) -> Credentials:
...
def _convert_service_account(credentials: Any) -> Credentials:
...
```
But it's not ideal, because it's not type safe. I think, we can add try-except imports to functions body:
```python
def _convert_oauth(credentials: Any) -> Credentials:
try:
from oauth2client.client import OAuth2Credentials, AccessTokenCredentials, GoogleCredentials
except ImportError:
pass
...
```
NamedTuples are used for options, but it's not proper way to use them. …
=> #966  Add sketch typing for utils.py

gspread/worksheet.py, tests/cassettes/WorksheetTest.test_update_title.json, tests/cassettes/WorksheetTest.test_worksheet_update_index.json, tests/worksheet_test.py
Closes #1201
Many internal properties were not updated
These updates were also not tested for in the tests.
More info in #1201
=> Update (and test for) internal properties on change

gspread/utils.py, gspread/worksheet.py, tests/cassettes/WorksheetTest.test_get_values_and_combine_merged_cells.json, tests/utils_test.py, tests/worksheet_test.py
Implement feature suggestion from #700:
" Same value for all merged cells "
This is added as an optional (default off) feature of `Worksheet.get_values`
I would have edited #741 but it was very old so hard to edit without a git mess.
closes #700
closes #741
this is probably not done in the best way. I use an extra API request where I should perhaps just use the internal Worksheet._properties object. I can change this if requested.
note: this could also be implemented for `Worksheet.row_values` and `Worksheet_get`, but I did not do so, because I did not want to play with `ValueRange`...
=> 700-fill-merged-cells

gspread/utils.py, gspread/worksheet.py, tests/cassettes/WorksheetTest.test_get_values_with_args_or_kwargs.json, tests/worksheet_test.py
Remove the function decorator accepted_kwargs.
We can simply put all the args on the method signature.
The function filter_dict_values is useless too now, we can set
the params with some None values that does not break the API calls.
This:
- simplifies the method signature
- allows rich editors to find and display the right method signature
and not just `wrapper(*args, **kwargs)`.
- allows us to better type arguments
- allows us to set default value like any other method using `param=Defaultvalue`
- simplifies the code in general
closes #1228
=> Remove accepted_kwargs decorator

tests/spreadsheet_test.py, tests/worksheet_test.py
test output has a lot of space.
this removes some warnings for deprecated methods
there are still some warnings for future deprecated methods which should disappear in 6.0.0
=> remove deprecated methods from tests

docs/api/utils.rst, gspread/client.py, gspread/spreadsheet.py, gspread/utils.py, gspread/worksheet.py, pyproject.toml, test-requirements.txt, tests/worksheet_test.py
Most of the parameters for the API are `ENUM`s
Replace the named tuples that are not fitted for that with enums.
Each enum hold one of the choices.
The actual string value must be extracted in order to pass strings only to the API using the function `extract_enum_value` using the `enum.value` field if the enum is not `None`.
this forces us to filter all arguments that are passed when they can possibly be `None`.
thought about setting the default value for each instead but this changes the API call made to the API and that could lead to unwanted behavior for the users.
Possible way was to add a new value to each enum: `default = None` which will result in a `None` value so it won't be part of the API call, but this requires all method to have that value as default value, and if a user (for …
=> Remplace named tuples with enums

gspread/utils.py, gspread/worksheet.py, tests/utils_test.py
In the next major release we will update some method signature. In order to help users in the transition, add this new special value which allows a user to specify an argument as a regular arg and as a kwarg.
In the case of the breaking change of the method `Worksheet.update()` it will allow users to speficy the argument names and keep their code running when the update arrives with no changes.
closes #1264
=> Add required kwargs with no default value

gspread/utils.py, gspread/worksheet.py, tests/utils_test.py, tests/worksheet_test.py
closes #1272
- add warnings to `tab_color` property and `update_tab_color` methods that colors will be changing to hex in 6.0.0
- these warnings also say how to remove the warning (by switching to hex)
- method `get_tab_color` added so that there is a way to circumvent the warning
=> Add deprecation warnings for colors

docs/api/exceptions.rst, gspread/__init__.py, gspread/client.py, gspread/exceptions.py, tests/cassettes/ClientTest.test_access_private_spreadsheet.json, tests/cassettes/ClientTest.test_copy.json, tests/cassettes/ClientTest.test_import_csv.json, tests/cassettes/ClientTest.test_no_found_exeption.json, tests/cassettes/ClientTest.test_open_all_has_metadata.json, tests/cassettes/ClientTest.test_open_by_key_has_metadata.json, tests/cassettes/ClientTest.test_open_by_name_has_metadata.json, tests/client_test.py
replacement of #1245
closes #1244
(the following copied from #1245)
- remove `CellNotFound` exception
- `open` and `open_by_key` now return `SpreadsheetNotFound` exception (if spreadsheet not found), which extends `APIError`
- request is attached to SpreadshetNotFound as payload. Technically, `open` can make multiple requests, but only the latest is attached
- `open_by_key` returns `PermissionError` if client is not allowed to open the spreadsheet. This test is currently broken (see #1268)
=> Add better Exceptions on opening spreadsheets

gspread/utils.py, tests/cassettes/WorksheetTest.test_get_values_merge_cells_outside_of_range.json, tests/utils_test.py, tests/worksheet_test.py
closes #1298
merge_combined_cells was *very* broken. It threw an error anytime that there was a merged cell outside the requested range (including [as in #1298] merged cells on the border of the "all spreadsheet" range).
This fix:
- adds tests for the behaviour in #1298
- fixes those tests
Further, this bug will probably come up anytime anyone tries to use merge_combined_cells. Thus, I propose we:
=> Fix merge_combined_cells in get_values (AND 5.11.2 RELEASE)

.github/CONTRIBUTING.md, gspread/client.py, tests/cassettes/ClientTest.test_list_spreadsheet_files.json, tests/cell_test.py, tests/client_test.py, tests/spreadsheet_test.py, tests/worksheet_test.py
This pull request changes the return type of `list_spreadsheet_files` back to a list of dicts. A private method `_list_spreadsheet_files` does the heavy lifting and returns the tuple, to be consumed by `open`.
Fixes #1307
=> Fix list_spreadsheet_files return value

gspread/worksheet.py
closes #1310 
Fixed the warning message for the worksheet update method for better readability
=> Fix warning message for `worksheet.update` method

README.md, gspread/auth.py, gspread/client.py, gspread/utils.py, gspread/worksheet.py
Anyone can silence all the deprecation warnings using the env variable
GSPREAD_SILENCE_WARNINGS=1
closes #1323
=> allows users to silence deprecation warnings

README.md, gspread/utils.py, gspread/worksheet.py, tests/cassettes/WorksheetTest.test_get_values_and_maintain_size.json, tests/cassettes/WorksheetTest.test_update_acell.json, tests/utils_test.py, tests/worksheet_test.py
closes #1289
Users can now specify `maintain_size=True`, so that "A1:C3" will always be a 3x3 array, regardless of whether the cells are full or not. See #1289 more more explanation.
```python
>>> worksheet.get_values("A1:D4")
[
["1", "2"],
["3", "4"],
["5", "6"],
]
```
```python
>>> worksheet.get_values("A1:D4", maintain_size=True)
[
["1", "2", "", ""],
["3", "4", "", ""],
["5", "6", "", ""],
["",  "",  "", ""],
]
```
In the future (6.0.0), this could be changed to be default behaviour. Thoughts?
=> Add `maintain_size` to keep asked for size in `get`, `get_values`

.github/workflows/main.yaml, gspread/client.py, gspread/http_client.py, gspread/utils.py, gspread/worksheet.py, lint-requirements.txt, tox.ini
closes #1321
I have added `mypy` type checking to the lint workflow, so it now runs when you run
```bash
tox -e lint
```
I also fixed some typing problems. `mypy` now runs without error.
Is there anything else to type @lavigne958? or is this everything?
=> Add type checking to lint

gspread/worksheet.py
Instead of using generic `kwargs`
Mention the argument `range` explicitly and add it's type.
closes #1090
=> Improve `Worksheet.sort()` signature

gspread/worksheet.py
this was not caught by #1296's CI because type-checking was not yet enabled in the workflow.
This is the main change:
```diff
- value = str(data.first())
+ try:
+     value = str(data[0][0])
+ except IndexError:
+     value = str(None)
```
...which replaces the call to `ValueRange.first()` with its implementation
https://github.com/burnash/gspread/blob/6944c1f94f29279b5412ba2e0606276ddbb1ad09/gspread/worksheet.py#L140-L148
The error was because before #1296, `get` returned a `ValueRange`. *After* #1296, it returns `ValueRange | List[List[Any]]`, so the type checking complained that `.first()` was not a method on `List[List[Any]]`. I'm not sure how to solve this issue by typinig, which is why I did what I did here.
Why is `.first()` needed as a function anyway? It is hardly used. I propose …
=> fix type issue (remove `.first()` function)

gspread/worksheet.py
closes #1332
`use_index` was added by #1301 to make implementing #808 easier in future
we can add it back later when the column-indexing functionality is added
=> remove `use_index` and references to it in `get_records`

gspread/auth.py
now, if a user does not specify client_factory, they will not get a warning
=> make deprecation warning dependent on if kwarg is used for client_factory

gspread/worksheet.py, tests/cassettes/WorksheetTest.test_get_all_records_expected_headers.json, tests/worksheet_test.py
closes  #1352 
See #1352 for more information.
- make `expected_headers` test fail (by making headers duplicate)
- fix test (by moving unique check to the `if expected_headers == None` branch)
=> fix 1352 expected headers broken

gspread/utils.py, gspread/worksheet.py, tests/cassettes/WorksheetTest.test_get_values_and_combine_merged_cells.json, tests/cassettes/WorksheetTest.test_get_values_merge_cells_from_centre_of_sheet.json, tests/cassettes/WorksheetTest.test_get_values_merge_cells_with_named_range.json, tests/utils_test.py, tests/worksheet_test.py
closes #1330 
add `start_row_index` and `start_col_index` to `utils.combined_merge_values` so that ranges that don't start at col 0, row 0 (i.e., `A1`) can have their merged cells merged.
n.b., not starting from the top left introduces more issues with `combine_merged_cells` -> #1334
This code is added to `worksheet.get_values`. This is to get the `start_row_index` and `start_col_index` from the requested range.
https://github.com/burnash/gspread/blob/0e698de225dadbce97e9bb085ed2ad1eaa7d22ce/gspread/worksheet.py#L495-L503
=> fix `combine_merged_cells` when using from a range that doesn't start at `A1`

gspread/worksheet.py
when calling `worksheet.update` with the swapped argument order I didn't get a warning
so I changed the stacklevel until I did (to 2)
I still don't properly understand stacklevel, and this will not emit a warning if the user uses `update` in another of their own functions, only from a root file. In this way I don't think using `warnings.warn` is great.
Anyway, this is a plaster/band-aid fix.
=> increase warning stacklevel from 1 to 2

docs/api/utils.rst, gspread/utils.py, gspread/worksheet.py, tests/cassettes/WorksheetTest.test_get_merge_cells_and_unmerge_cells.json, tests/worksheet_test.py
Fixed default value of merge_type parameter in merge_cells function docstring.
=> Fixed default value of merge_type parameter in merge_cells function docstring.

gspread/utils.py, gspread/worksheet.py, tests/utils_test.py
Add a new util function that helps building record values. Records are list of dictionaries, each dictionary has the same set of keys, they are set from the given list of headers. Each key is associated to a value from the given matrix of values. They are as many dictionaries as they are lines in the matrix.
Each line in the matrix will be associated to a dictionary, each key is associated to a value from that line in the given order.
Example:
Headers: A B C
Values:
1 2 3
7 8 9
Result: [ { A: 1, B: 2, C: 3}, {A: 7, B: 8, C: 9}]
closes #1367
=> Add util function `to_records` to build records

gspread/auth.py, gspread/client.py
Allow new `gspread.client.Client` to be initialized using an external `requests.Session` object.
closes #1383
=> Allow client to use external Session object

pyproject.toml, tox.ini
It was removed already by #1234.
It found its way back in, somehow.
closes #1391
=> Remove-py-3.7-support

gspread/auth.py
closes #1394 
Firstly, this fixes the typo `scopres` -> `scopes`
Secondly, it changes the typing from `Callable` to `Protocol`, so that this issue is caught by the `mypy` linting. e.g., in [this workflow](https://github.com/burnash/gspread/actions/runs/7727465761/job/21066000327)
```bash
Found 1 error in 1 file (checked 10 source files)
gspread/auth.py:284: error: Unexpected keyword argument "scopres" for "__call__" of "FlowCallable"; did you mean "scopes"?  [call-arg]
lint: exit 1 (4.30 seconds) /home/runner/work/gspread/gspread> mypy --install-types --non-interactive --ignore-missing-imports ./gspread pid=1957
```
=> Fix oauth flow typo

gspread/auth.py
closes #1390
Credentials object is renamed `OAuthCredentials` in v6.0.0, and is no longer `Credentials` type, so the type-check for "already logged in" was failing. See https://github.com/burnash/gspread/issues/1390#issuecomment-1919494986 for more context.
It is worth noting that types were being checked with `type()`. This it not reccomended as per [pylint](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/unidiomatic-typecheck.html).
If we had been using `isinstance`, this bug would not appear, as
`if not type(creds) is Credentials:` did not work with `OAuthCredentials`
`if not isinstance(creds, Credentials):` would have worked with `OAuthCredentials` as it is a subclass of `Credentials`
Thus, the result of this change is only tested manually, by me, on my …
=> check oauth creds type using `isinstance`

gspread/worksheet.py
Hi, I changed the type hints for the `in_row` and `in_column` arguments of the find method in `worksheet.py` from `Optional[bool]` to `Optional[int]`. 
Could you check this later?
=> Fix type hints at find method in worksheet.py

gspread/cell.py, gspread/utils.py, gspread/worksheet.py, tests/cassettes/WorksheetTest.test_cell_return_first.json, tests/worksheet_test.py
Fixup regression where getting a cell
on an empty cell should return a valid `Cell`
object with a value `None`.
closes #1403
=> Fixup get empty cell value is `None`

gspread/spreadsheet.py, gspread/worksheet.py, tests/cassettes/WorksheetTest.test_attributes.json, tests/worksheet_test.py
The `Worksheet` object was missing the `spreadsheet` attribute.
Add it back to be backward compatible.
closes #1395
=> Fix missing attribute `spreadsheet` in `Worksheet`.

README.md
closes #1408
- add `Worksheet.__init__` change
- hide "rarer" changes under `<details>` so users are not overwhelmed by changes, and can get to "more examples" easier
guide now looks like (see [on branch](https://github.com/burnash/gspread/tree/af9eb4a9ed81ad1d428c9a3b0835439af9c760a7/))
I have hidden some of the suggested migration changes, as I think they are less important. I think it is more important for people reading the README to get to the `More Examples` section, especially if they are new to the library.
Thanks. Let me know if you think we should change this at all. Or just push to the branch :)
After this we can release 6.0.1?
=> update migration guide

gspread/exceptions.py, gspread/http_client.py, tests/cassettes/ClientTest.test_access_private_spreadsheet.json, tests/client_test.py, tests/conftest.py
Catch usage limit errors from the Drive API. it returns the HTTP code 403 (access denied) on usage limits and access denied. Find the difference in both case and retry when it's usage limits exceeded.
Improve back-off client code.
Add pretty print for the APIerror Exception.
closes #1268
closes #1326
=> Improve back-off client

docs/oauth2.rst, gspread/__init__.py, gspread/auth.py
Add a new auth method that allows users to open public spreadsheet files with a simple API key.
closes #1096
=> Add new auth method API key

gspread/worksheet.py
The multi-line string in the code concatenates imperfectly when actually printed. Need to include spacing manually, unless one gets
> the header row in the worksheet is not uniquetry passing [...snip...]
=> fix error message readability

gspread/client.py, gspread/http_client.py, gspread/utils.py
Prior to v6.x.y the method could be used as follow:
file = client.open('x')
file.client.import_csv()
Now file.client is of type HTTPClient
so we need to add the method back for backward compatibility
closes #1423
=> Add missing method `import_csv()`

tests/conftest.py
I tested it, when you add new HTTP requests into a test, or a new test and just run the test suite with no env variables then it prints the new exception.
the output is quiet verbose though :roll_eyes:  it still prints the output from the VCR exception.
It looks like this:
```
collected 135 items / 134 deselected / 1 selected                                                                                                                                                                                            
tests/worksheet_test.py::WorksheetTest::test_acell FAILED
================================================================================================================== FAILURES ====================================================================================================== …
```
=> Add user friendly message when we can't override a test cassette

gspread/worksheet.py, tests/cassettes/WorksheetTest.test_add_protected_range_normal.json, tests/cassettes/WorksheetTest.test_add_protected_range_warning.json, tests/cassettes/WorksheetTest.test_delete_protected_range.json, tests/worksheet_test.py
closes #1437
They were not allowed before because:
It seems that when `add_protected_range` was added it was assumed that `editor_users_emails` was always required. However, warning ranges do not require (and in fact, cannot contain) emails.
To fix this issue, we:
- change `editor_users_emails` from and `argument` to a `keyword argument` (if it is not changed in position, it should still be usable as an argument)
- add some logic in the code to not pass "editors" if `warning_only` is set
=> Allow "warning" type protected ranges

README.md, docs/user-guide.rst
=> Improce README and documentation with value render options

gspread/client.py, gspread/http_client.py, gspread/spreadsheet.py, gspread/utils.py, gspread/worksheet.py
Introduce a lot of `Any` Typing is most method in the `Spreadsheet` object return some JSON object and we can't type it.
ref: #1430
=> Add some missing typing in code

README.md, docs/index.rst, docs/user-guide.rst, gspread/auth.py, tests/worksheet_test.py
Fixes similar to #1431  for docs, a docstring and a test.
- `Worksheet.update` default argument ordering is now `Worksheet.update(<values>, <range name>, ...`
- Single cell updating uses the `Worksheet.update_acell` method now
=> More fixes for `Worksheet.update` argument ordering & single cell updating (i.e. now `Worksheet.update_acell`)

README.md, docs/user-guide.rst, gspread/utils.py, gspread/worksheet.py, tests/cassettes/WorksheetTest.test_add_validation.json, tests/worksheet_test.py
Added a RealtiveDate enum
removed the realtive date enum
Closes #1420
=> Added 'add_data_validation` to `Workhsheet` [Issue #1420]

gspread/worksheet.py
get_note can only get the content of the note located at one cell, we need get_notes to get all notes in the sheet
=> add `get_notes`

gspread/client.py
When a user request to copy a spreadsheet it can request to copy the source spreadsheet permissions too.
When copying the permissions these could be of type:
- Anyone (no email address)
- User or Group: an email address exists
- Domain: no email address exists but a domain instead
extract the right information and pass it to the lower level method that will handle it depending on the type.
closes #1457
=> bugfix: handle domain name in spreadsheet copy permissions

.github/workflows/main.yaml
ignore pip vulnerabilities in CI, we don't ship pip.
=> Ignore pip vulnerabilities in CI.

.github/CONTRIBUTING.md
I run tests without `tox`. I find this easier.
I think people should have this knowledge. They should also know that the CI runs tests with tox.
Also removed `-v` (verbose) and `-s` (silence stderr/stdout) as I do not think these are useful, and having lots of extra CLI arguments is imposing for new CLI users.
=> add note about runnings tests to contrib guide

gspread/client.py
In gspread client add a new property expiry which returns the expiry datetime object from the used credentials.
The expiry only exists for OAuth credentials otherwise it returns None.
=> Add property expiry in gspread client

README.md
Small fix to correct formatting of code block example in README for "Add data validation to a range".
Before:
After:
=> Fix code block formatting typo in README

.github/workflows/main.yaml, gspread/auth.py
fix CI by skiping unwanted CVE report.
fix CI by updating typing on google auth library
closes #1478
=> ignore jinja CVE

tests/cell_test.py, tests/client_test.py, tests/conftest.py, tests/worksheet_test.py, tox.ini
=> Type part of test suite utils

gspread/exceptions.py, tests/worksheet_test.py
First, thanks for this tool!
We have a pipeline where exceptions from packages such as `gspread` are pickled and stored for further processing. Unfortunately, the `APIError` exception is not able to be unpickled as the args it passed to the `Exception` super are different from what is passed into the exception itself.
The sample test extension exposes this error as seen below:
```
def __init__(self, response: Response):
super().__init__(self._extract_error(response))
self.response: Response = response
>       self.error: Mapping[str, Any] = response.json()["error"]
E       AttributeError: 'dict' object has no attribute 'json'
gspread/exceptions.py:45: AttributeError
```
This PR ultimately only replaces the extracted error with the raw response passed to the kwargs. Given that `__str__` …
=> Remove passing exception as args to super in APIError

gspread/http_client.py
Fix incorrect documentation regarding BackOffHTTPClient.
Perhaps it's an omission of the change at https://github.com/burnash/gspread/pull/1190 .
=> Fix docstring about BackOffHTTPClient

gspread/auth.py
- Updated the comment in `gspread/auth.py` to indicate that the `api_key` feature is available starting from `google-auth` version `2.15.0`.
The previous comment incorrectly stated that the `api_key` feature was available from version `2.4.0`. This has been corrected to `2.15.0`.
- **v2.14.1**: 
- **v2.15.0**:
=> Fix comment to reflect correct google-auth package version requirement

gspread/utils.py, gspread/worksheet.py
=> fix: fix type annotation for default_blank

gspread/exceptions.py
Possibly we encountered an error while parsing the API error JSON, like connection closes early etc and the received JSON is invalid.
Better handle such scenario and build a valid error Dict to keep the exception stack flow running and raise this message to the application.
extract the returned text so if we any bit of valid information at least we can pass that to the application.
This could be helpfull to if we add calls to the API made for web browser that returns HTML error message, it will fail to decode the recieved error and raise a proper error.
closes #1504
=> better handler API error parsing.

tests/cassettes/SpreadsheetTest.test_bad_json_api_error.json, tests/conftest.py, tests/spreadsheet_test.py
Manually build an invalid JSON body. Using HTML to fake using the wrong endpoint that returns HTML instead of JSON.
Use that new http client to do some request and make sure the error matches.
=> Add test on receiving an invalid JSON in the APIError exception handler.

docs/user-guide.rst, gspread/utils.py, gspread/worksheet.py, tests/utils_test.py
Add a new feature that allows a user to expand a cell range
into a table.
the expand will look for the right most cell with adjacent value.
the expand will look for the bottom most cell with adjacent value.
the expand will table down from top left celle range to bottom right
value.
closes #1414
=> [feature] Add 'expand_table' feature

gspread/worksheet.py, tests/cassettes/WorksheetTest.test_batch_merged_cells.json, tests/worksheet_test.py
=> Created a `batch_merge` function [Issue #1473]

gspread/worksheet.py
Apologies for the trivial PR, but I noticed a typo and figured I'd clean up some of the grammar in this docstring at the same time. Cheers, and thanks for making `gspread`.
=> Documentation update for gspread.worksheet.Worksheet.get_all_records

gspread/__init__.py, tox.ini
Currently, gspread uses implied exports for all of its externally-accessible symbols. This works fine, but it makes some type checkers complain. In particular, pylance (the default type checker for python in VSCode) flags an issue. mypy will as well, if run with the `--no-implicit-reexport`.
The following script can be used to see this in action:
```
#!/usr/bin/env python3
import gspread
gspread.service_account(filename="example.json")
```
pylance will return this warning: `"service_account" is not exported from module "gspread"`
mypy --no-implicit-reexport will return: `error: Module "gspread" does not explicitly export attribute "service_account"  [attr-defined]`
Some brief notes about implicit and explicit exports are available in the mypy documentation, see e.g. …
=> explicitly list exported package symbols

README.md, docs/oauth2.rst
As discussed in #145, help newbies by clarifying the step between `import` and opening a spreadsheet. Make it clearer what your options are and how to choose. This was originally motivated by the confusion about how to use the library when your spreadsheet is shared with "anyone with the URL".
=> Clarify the first step: authentication

.github/workflows/main.yaml, gspread/worksheet.py
When I get this error, I would like to go find the problematic column in the sheet and then fix it. This was difficult before, now it is easy.
Also, fixup the lint action in CI, because I was running into errors:
- We don't need to install mypy (the tox env does that for us)
- We only run this on python versions 3.8+, so the version check isn't needed
- Upgrade the usage of `safety` from the 2.x CLI version to the 3.x version (https://docs.safetycli.com/safety-docs/safety-cli/migrating-from-safety-cli-2.x-to-safety-cli-3.x). Before, we were getting `DEPRECATED: this command (`check`) has been DEPRECATED, and will be unsupported beyond 01 June 2024.` and this caused an error in https://github.com/burnash/gspread/actions/runs/14607328648/job/40978873165?pr=1548
- Pin the version of safety …
=> Include the duplicate column names in error message
