burnash/gspread

- docs/oauth2.rst
@burnash I added a workaround for Python 3 users in the oauth docs.
> added workaround for python3 users

- gspread/models.py
This helps to clarify issues like #67.
> Note that append_row() may be right at the bottom of a new sheet.

- tests/test.py
Fixed broken tests and improved WorksheetTests.
> Fixed failing tests, refactored WorksheetTests

- docs/oauth2.rst
> Make Documentation Current

- gspread/client.py
This cuts memory usage by half for large spreadsheets.
> Use celementtree when available to reduce memory usage

- gspread/client.py
- gspread/utils.py
- tests/test.py
> fix regex for #349, refactor id extraction; add tests

- README.md
- gspread/models.py
- gspread/utils.py
- tests/mock_tests.py
- tests/test.py
- tests/tests.config.example
- tox.ini
I need to use this feature in my work and found there's no api to get gid. Luckily there are solutions on [SO](http://stackoverflow.com/questions/11290337/how-to-convert-google-spreadsheets-worksheet-string-id-to-integer-index-gid). I tested it and it works perfect!
Not sure if you're interested in adding this feature. If you do, I'll add some test cases.
> Added gid property for worksheets

- gspread/client.py
Closes #492. No tests or anything, but seems to work.
> allow setting the withLink property of permissions

- gspread/v4/models.py
This fixes using this endpoing when the worksheet name has forward
slashes or other strange characters.
> URL encode the range in the value_* functions

- docs/api.rst
- docs/index.rst
- docs/oauth2.rst
- docs/user-guide.rst
This moves generated API docs to a separate file and adds the new index file.
> Move api docs to a separate file

- gspread/models.py
This PR adds ability to duplicate a worksheet and closes #452
> Add ability to duplicate a worksheet

- tests/cassettes/SpreadsheetTest.test_values_get.json
- tests/test.py
This PR adds a test case that should cover #554, #558, #605 
Related fix is #596
> Add a test case and a cassette for Spreadsheet.values_get

- gspread/models.py
- gspread/utils.py
> Fix KeyError in urllib.quote in Python 2

- docs/oauth2.rst
"APIs & auth" menu deprecation + fix exception value + remove outdated images
> Update oauth2.rst - deprecated menus and outdated images

- gspread/client.py
- gspread/urls.py
> Use Drive API v3 for creating and deleting spreadsheets

- gspread/utils.py
Otherwise, that single test is failing in Travis.
> Update numericise with underscores test to work in python2 and <python3.6

- gspread/models.py
- gspread/utils.py
- tests/test.py
These allow you to freeze columns and/or rows and to create a basic filter on a set of data.
This would fix #543.
> Add freeze and add_filter functions to Worksheet

- gspread/models.py
- tests/test.py
Add the function in the Worksheet model to merge cells.
> Add cell merge function

- gspread/models.py
Change `Worksheet` method names to align them with respective Sheets API request names (SetBasicFilterRequest, ClearBasicFilterRequest):
* add_basic_filter → set_basic_filter
* remove_basic_filter → clear_basic_filter
> add_basic_filter → set_basic_filter, remove_basic_filter → clear_basic_filter

- gspread/models.py
> Fix Python 2 SyntaxError in models.py

- gspread/models.py
delete_column(self, index):
Deletes the column from the worksheet at the specified index.
param index: Index of a column for deletion.
> Added delete_column() method

- gspread/models.py
Regarding issue #447, add protect ranges in worksheet
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/sheets#ProtectedRange
> add worksheet protected range for issues #447

- gspread/models.py
I have a problem with the find() function i cannot specify a column so i made this changes to the function
> Adding col code to find

- gspread/models.py
> added duplicate_to

- gspread/models.py
> Fix ValueRange.from_json() method

- gspread/__init__.py
- gspread/auth.py
> Add auth.service_account_from_dict

- gspread/models.py
I've noticed that insert_row and insert_rows implemented identically, so one can be implemented in terms of the other.
> Simplify implementation of insert_rows via insert_row

- gspread/models.py
- gspread/utils.py
- tests/test.py
Implements feature request #746
> adding value_render_option parameter to get_all_records

- gspread/auth.py
- gspread/client.py
- gspread/models.py
Hello,
This is just a handful of fixed typos from various docstrings and one sentence I rephrased so it's easier to understand.
This is my first ever contribution to any open source software. Thanks for maintaining a great package that makes my life a lot easier!
> minor documentation fixes

- gspread/client.py
Fixes burnash/gspread#805,
and also fixes burnash/gspread#678
> Add folder_id to copy

- docs/oauth2.rst
Updated some steps for creating keys in Google Developers Console
> Added steps for creating new keys

- gspread/models.py
- tests/test.py
Adds the worksheet.get_note() method requested in #849, with relevant test cases.
> Add get_note method (#849)

- README.md
Updated get_all_values (deprecated) method to get_values
> Updated get_all_values (deprecated) method to get_values in README

- tox.ini
@lavigne958 Your review please.
> tox.ini: envlist = py36,py37,py38,py39

- gspread/models.py
Related to https://github.com/burnash/gspread/issues/908
> add deprecation warning for delete_row method in documentation

- .github/workflows/lint_python.yml
https://docs.github.com/en/actions/guides/building-and-testing-python#running-tests-with-tox
> lint_python.yml: Try 'tox -e py' to test current Python

- gspread/spreadsheet.py
- gspread/worksheet.py
- tests/cassettes/CellTest.test_define_named_range.json
- tests/cassettes/CellTest.test_delete_named_range.json
- tests/cell_test.py
For feature request #833.  Let me know if this looks alright.  I tried running the tests but couldn't get them to work for the 2 tests I added and kept getting 'Requested entity was not found'.  Other than the packages, are there any other requirements for running the tests?
> add functions for defining, deleting and listing named ranges

- gspread/utils.py
After upgrading to version 5.0.0, the work in my project broke due to the use of lower case.
> Аutomatic conversion of a cell letter to uppercase

- docs/user-guide.rst
Usage limits updated to reflect new limits on https://developers.google.com/sheets/api/limits
> Updated API rate limits

- gspread/worksheet.py
- tests/cassettes/WorksheetTest.test_group_columns.json
- tests/cassettes/WorksheetTest.test_group_rows.json
- tests/worksheet_test.py
Add new methods to work over `dimensionGroup`.
Possible actions are:
- add new group
- list groups
- delete a group
closes https://github.com/burnash/gspread/issues/1005
> Add new methods to add/list/delete dimensionGroups

- gspread/client.py
- gspread/utils.py
- lint-requirements.txt
Upgrade `black` version to 22.3.0 to work with python3.10
closes #1015
> Bugfix/black python3.10

- gspread/worksheet.py
- tests/cassettes/WorksheetTest.test_hide_show_worksheet.json
- tests/worksheet_test.py
Add a new method to hide or show a worksheet.
Currently we cannot retrieve the hidden state of a sheet,
see issue: https://issuetracker.google.com/issues/229298342
Add basic test.
Closes #995
> add new method to hide/show a worksheet

- gspread/worksheet.py
- tests/cassettes/WorksheetTest.test_auto_resize_columns.json
- tests/worksheet_test.py
Add a test on the method `auto_resize_columns`.
We cannot test the method `auto_resize_rows` because it requires the use
of the web browser to force the size of a row manually.
> Add test on `auto_resize_columns`

- gspread/worksheet.py
- tests/cassettes/CellTest.test_merge_cells.json
- tests/cell_test.py
Add new method to unmege previoysly merged cells.
Closes #997
> Add method to unmerge cells

- gspread/worksheet.py
This method allows end-user to format multiple non-overlapping ranges in
a single API call.
Updated method `format` to accept a `str` for a single range or a `list`
of `str` to apply the same format to multiple non overlapping ranges.
Closes #929
> Add new `batch_format` method.

- gspread/auth.py
- setup.py
Use the library pathlib for handling all files.
closes #1056
> Use pathlib

- gspread/client.py
> Add missing documentation on `set_timeout`

- gspread/client.py
> Fix grammar in docstring for client.export

- gspread/utils.py
- gspread/worksheet.py
- tests/cassettes/WorksheetTest.test_update_tab_color.json
- tests/worksheet_test.py
closes #996 
Add a new method to change the color of a tab.
Most of the work has been done by @cgkoutzigiannis.
> add method to change the color of a tab

- LICENSE.txt
Updated the outdated copyright year to the present.
> chore: Update outdated LICENSE year

- .github/dependabot.yaml
> add dependabot to maintain dependecies

- .github/workflows/main.yaml
Trigger on all branches, like before
but do not trigger on tags, the workflow `release.yaml` will be triggered
> improve trigger on CI

- docs/user-guide.rst
Include warning/note when opening Google Sheets using titles
> Update user-guide.rst to include a warning

- docs/user-guide.rst
>  Fixed typo in docs/user-guide.rst

- gspread/worksheet.py
- tests/cassettes/WorksheetTest.test_worksheet_notes.json
- tests/worksheet_test.py
Add new methods to insert/update/clear notes by batch of notes.
The simplest and most logical format found is:
- using a dict to pass the list of notes. with the following format:
- key: the cell where to attach the note
- value: the note content
closes #988
> Add batch notes insert/update/clear

- gspread/auth.py
- gspread/client.py
- gspread/utils.py
> Add deprecation warning for future release 6.0.x

- gspread/worksheet.py
- tests/cassettes/WorksheetTest.test_hide_gridlines.json
- tests/cassettes/WorksheetTest.test_show_gridlines.json
- tests/worksheet_test.py
closes #1197 
- add property [`Worksheet.is_gridlines_hidden`]
- add private method [`Worksheet._set_gridlines_hidden_flag`]
- add public methods [`Worksheet.hide_gridlines`] and [`Worksheet.show_gridlines`]
- add tests [`WorksheetTest.test_hide_gridlines`] and [`WorksheetTest.test_show_gridlines`]
[`Worksheet.is_gridlines_hidden`]: https://github.com/alifeee/gspread/blob/40e8f91b4f2be8c83a31f108b523c784d6653a37/gspread/worksheet.py#L192
[`Worksheet._set_gridlines_hidden_flag`]: https://github.com/alifeee/gspread/blob/40e8f91b4f2be8c83a31f108b523c784d6653a37/gspread/worksheet.py#L2748
[`Worksheet.hide_gridlines`]: https://github.com/alifeee/gspread/blob/40e8f91b4f2be8c83a31f108b523c784d6653a37/gspread/worksheet.py#L2770
[`Worksheet.show_gridlines`]: …
> FEATURE: show/hide gridlines (#1197)

- gspread/utils.py
- gspread/worksheet.py
- tests/cassettes/WorksheetTest.test_get_all_values_date_time_render_options.json
- tests/worksheet_test.py
Spelling fix: #1187
Legacy fix: #1205
This is a combination of the two, because pull requests and git are confusing.
> Spelling fix (with legacy option)

- gspread/worksheet.py
The function signature will change in the coming release 6.0.0
Add a warning for all users.
> Add_deprecated_warning_sort_method

- gspread/worksheet.py
this is how other methods like `update_title` and `update_index` do it. means that the request must succeed to update internal props.
> update self._properties after batch_update

- gspread/worksheet.py
> Add breaking change warning in Worksheet.update()

- .readthedocs.yaml
- docs/requirements.txt
Fix sphinx version to pass read the doc
closes #1220
> add read the doc configuration file

- lint-requirements.txt
update flake8 from 5.0.4 to 6.0.0
replacement of #1150
> bump flake8 to 6.0.0

- gspread/utils.py
- tests/utils_test.py
to help with beginners for #985
> add test_fill_gaps and docstring for fill_gaps

- gspread/worksheet.py
1. add property `column_count`
as mentioned in #1273 
2. remove warning from docstring (fixed in #1211)
> Add `column_count` prop as well as `col_count`

- gspread/spreadsheet.py
closes #1293
users should use get_lastUpdateTime instead
> remove lastUpdateTime

- gspread/utils.py
> change lambda function to dict (fix pyupgrade issue)

- gspread/worksheet.py
remove `get_records` (see #1332)
> Remove/get records   use index

- README.md
> change `worksheet.update` migration guide

- README.md
Backport the migration guide to master branch in order for everyone to see it before we release v6.0.0
> Add migration guide for get_all_records

- gspread/utils.py
- pyproject.toml
- test-requirements.txt
> Remove StrEnum dependency and added custom class[issue #1462]

- gspread/worksheet.py
- tests/cassettes/WorksheetTest.test_get_notes.json
- tests/cassettes/WorksheetTest.test_worksheet_notes.json
- tests/worksheet_test.py
1. add test for get_notes
2. add an example in documentation
3. get_notes return [[]] instead of [] if there are no notes
See [#1251 (comment)](https://github.com/burnash/gspread/pull/1451#issuecomment-2084156934) for more details.
> Some updates on `get_notes`
